<?php

namespace LongLiveBundle\Repository;

/**
 * CheckResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckResponseRepository extends \Doctrine\ORM\EntityRepository
{
}
