<?php

namespace LongLiveBundle\Repository;

/**
 * RuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuleRepository extends \Doctrine\ORM\EntityRepository
{
}
